version: "3.3"

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  burpinternetserver:
    build: 
        context: ./burp
        args:
            - DomainWhoami=my-subdomain-for-burp.*.com
            - IPWhoami=174.0.0.0
    image: s1r1u5/burpinternet:latest
    restart: always
    ports:
        - 53:53/tcp
        - 53:53/udp
        - 80:80
        - 587:587
        - 465:465
        - 443:443
        - 25:25/tcp
        - 9443:9443

    volumes:
        - /etc/letsencrypt/:/etc/letsencrypt/
        - ./logs:/var/log/burpsuite

    networks:
        frontend:
            ipv4_address: 172.20.0.5
